POST http://localhost:3001/api/blogs
Content-Type: application/json

{
  "title": "Janne Kalastaa & lumen",
  "author": "Janne",
  "url": "www.jannen-kala-blogi.fi",
  "likes": 1,
  "userId": "6206405b5267a8f6d26927f1"
}